### ISSUE TITLE
Add additional <self-uri> tag to hold Figures PDF file name

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#100]
## Problem / Motivation

- **WHO wants this?**  Production
- **WHEN and WHERE do they want it?** In article XML, in the `<article-meta>` section, to add an additional `<self-uri>` tag, where there currently already exists a tag for the article PDF file
- **WHAT do they want?** An additional `<self-uri>` tag where the `xlink:href` attribute is set to the Figures PDF file, when present
- **WHY do they want this?** To make the presence of the file explicitly mentioned in the JATS XML

## Proposed solution

After some initial email discussion, there are some points where these values may have an impact, however if the proposed is followed it will probably have the least negative impact:

- Add `<self-uri>` tag, optionally -- when a figures PDF file exists.
- The `content-type` attribute value in the tag is important, because currently `content-type="pdf"` already denotes the article PDF, so a value other than `"pdf"` would be ideal for this additional `<self-uri>` tag
- Can test an example on the `continuumtest` environment to ensure compatibility with publishing workflows

## Clarification needed and assumptions

- Workflow / elife-bot notes: the `ApplyVersionNumber` activity renames all the tags with an `xlink:href` attribute where there is a matching file name in the folder. This currently happens on the existing `<self-uri>` tag, and would likely also happen on additional `<self-uri>` tags, but it is best to test this
- Crossref notes: the existing `<self-uri>` tag value is used to generate Text and Data Mining URLs for reporting to Crossref, and is why the `content-type="pdf"` value is important to remain as it is
- Lens uses the `<self-uri>` tag file name value to guess at the version number of the XML file it is rendering, to load correct figure image assets
- Note: The PoA XML generation process currently adds a `<self-uri>` tag for the article PDF file, but it shouldn't need to add anything for a figures PDF file, since those are not individually separated out for articles of that status

---

## Tasks

Not listed in a particular order

- [x] Decide on the `content-type` attribute value to use on the new `<self-uri>` tag, proposed value: `figures-pdf`
- [x] Update kitchen sink XML with the additional `<self-uri>` tag
- [x] Prepare a zip file containing the new XML and PDF files and test it on `continuumtest` environment
- [x] Test the XML file in Crossref generation
- [x] Test the XML file in Lens
- [x] Deployment steps TBD - I believe @Melissa37 will coordinate with ExeterPremedia to alter the XML

## Technical notes
- We could use this technology
- More notes or suggestions

## User interface / Wireframes

@FAtherden-eLife I created the issue here, since it seems to be most applicable to be part of XML-mapping. CC @Melissa37 discussion about tagging and naming can continue here.

**Comment by fred-atherden** [comment]
I have added an extra `self-uri`, `<self-uri content-type="figures-pdf" xlink:href="elife-54098-figures.pdf"/>`, and loaded a test file to Continuum test - `elife-54098-vor-r2.zip`.
https://continuumtest--ppp-dash.elifesciences.org/article/54098

As far as I can tell, the article remains unaffected, as does Lens and download options. Version number still seems to operate as expected.

**Comment by fred-atherden** [comment]
[Kitchen sink PR](https://github.com/elifesciences/XML-mapping/pull/101)

**Comment by fred-atherden** [comment]
This has been added to the XML for a long time now, and everything is working great, so closing.
