### ISSUE TITLE
Remove component DOIs and add new Peer review material DOIs

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#87]
## Problem / Motivation
We have completed research into the usage in the wild of our component DOIs:
https://docs.google.com/document/d/1zNvATamoQc4vcTk6OHqQmLRnwAGr4685l35e2RGeoWs/edit
It is so low that we've taken the decision to stop publishing them. This will speed the development of Texture and integration into our new production process.  

- WHO wants this - eLife production team
- WHEN and WHERE do they want it - in the production and publishing workflow, including downstream deliveries (especially Crossref)
- WHAT do they want - stop producing and registering component DOIs with Crossref; start producting Peer Review DOIs for the decision letter and author response (change the suffix of the current component DOI)
- WHY do they want this - nobody makes use of component DOIs and they cause unnecessary complication 

## Proposed solution
Stop producing and registering component DOIs in the production workflow
Start producing and registering DOIs for Decision letters and Responses. Will use the eLife component DOI structure of adding a suffix to the main DOI, of .DL and .AR, eg
10.7554/eLife.42687.DL
10.7554/eLife.42687.AR
These will be registered with Crossref using the new schema for peer review materials (see https://github.com/elifesciences/elife-crossref-feed/issues/123)

## Clarification needed and assumptions
An assumption is that this will not break Continuum and require development work at that end of the workflow but needs testing
An assumption is that Exeter can do this easily in the Kriya workflow
An assumption is that this will not break the JATS XML to Crossref XML workflow

---

## Tasks

- [x] Run a few articles through the text continuum site with no component DOIs and the newly structured DOIs for peer review materials
- [x] Co-ordinate the depreciation and development of this feature with Exeter (https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/issues/216)
 - [x] Co-ordinate the depreciation and development of this feature with Crossref development workflow (https://github.com/elifesciences/elife-crossref-feed/issues/123 and https://github.com/elifesciences/elife-crossref-feed/issues/140)
 - [x] Check with Dev team whether component DOIs have any implications elsewhere in the workflow or database store

## Technical notes
@gnott 
@thewilkybarkid 
@giorgiosironi 
@lsh-0 

## User interface / Wireframes
NA

@gnott

**Comment by Melissa37** [comment]
>* Run a few articles through the text continuum site with no component DOIs and the newly structured DOIs for peer review materials

See:
https://continuumtestpreview--journal.elifesciences.org/articles/42690v1

However kitchen sink stalls at first stage - suspect this is to do with Videos? @gnott can you de-bug?
It does not fail..

![screenshot 2019-02-27 at 16 42 57](https://user-images.githubusercontent.com/6051876/53506943-e90a5600-3aae-11e9-8a80-0143e0588fcc.png)

**Comment by giorgiosironi** [comment]
To help the investigation, https://alfred.elifesciences.org/job/test-continuumtest/ checks nightly that the `continuumtest` environment can publish a very simple article, so it rules out simple configuration problems.

**Comment by gnott** [comment]
I think the input zip file you used in the test is named `elife-00666.r20.zip`. For best results, it should be named ~~`elife-00666-vor-r20.zip`~~ edit: `elife-00666-vor-r23.zip` (there already is a `elife-00666-vor-r20.zip` file). I'm going to copy the original zip over to that file name and deposit it to the bucket to see what we get on run 2.

**Comment by gnott** [comment]
This is the run for it: https://continuumtest--ppp-dash.elifesciences.org/article/00666/10/ce0b4d6c-dc87-4086-9ec3-fcb00e988591

Fails on schema validation, which looks to be as simple as the digest is required to have a `doi`. If I add that into the JSON then the output is valid.

**Comment by gnott** [comment]
One question I have is regarding the existing backlog of articles, where the XML has component DOIs present. Do you want to omit and not report those to Crossref, even if they are in the XML? (I might come up with a new library setting value to "ignore_component_doi" for example, if that is the case).

**Comment by Melissa37** [comment]
>Fails on schema validation, which looks to be as simple as the digest is required to have a `doi`. If I add that into the JSON then the output is valid.

This is really promising! @thewilkybarkid is this an easy and quick thing to change?

**Comment by Melissa37** [comment]
> One question I have is regarding the existing backlog of articles, where the XML has component DOIs present. Do you want to omit and not report those to Crossref, even if they are in the XML? (I might come up with a new library setting value to "ignore_component_doi" for example, if that is the case).

No, I think if we publish a component DOI we have to register it and keep it active. Unless I've misunderstood the question @gnott ?

**Comment by gnott** [comment]
> No, I think if we publish a component DOI we have to register it and keep it active

Good answer for me, that we will continue to deposit component DOIs if they are present.

**Comment by gnott** [comment]
@

**Comment by Melissa37** [comment]
Exeter is getting together their quote for this and had a few questions.

As eLife regularly publish new versions of content, it's really hard for them to implement changes to workflows that have to account for both styles. For instance, we'd have to turn off the PDF generator each time for old content and for them to do it manually to ensure the component DOIs were included. Likewise, I'd rather components are stripped completely rather than risk them being hidden in some XML that we don't see and not others.
It is also a blocker for putting old content through Texture as that will not support component DOIs.

So, the plan is:
Exeter strip component DOIs from the eLife interface, XML process and PDF generation process.
If any articles are resupplied their new published version will not contain component DOIs.

@gnott Can we change the Bot process when we implement this - do not send new versions or silent corrections to Crossref. Therefore, the component DOIs that exist in their system remain and are not removed by a resupply. They have to remain as they are PIDs. They just won't be on the new versions of content

**Question** - the urls component DOIs link to, do they change when a new version is published and is that a problem? ie the components would link to an older version of content, whose url would have a .vX suffix?

eLife production will have to manually resupply to Crossref if we publish with a wrong date.

Does anyone see any other flaws in the plan or solutions to problems?

**Comment by gnott** [comment]
A thought related to Crossref that pops in my mind is, if a component DOI was created due to a previous deposit, and then if the next deposit does not include the component DOIs, do the component DOIs get removed from Crossref automatically, or do you have to explicitly go into Crossref to delete them? If they are "sticky" and live on even after simpler deposits then it might be less work required on our part.

**Comment by gnott** [comment]
> Can we change the Bot process when we implement this - do not send new versions or silent corrections to Crossref

We are currently not sending for silent corrections (however I planned to deposit when a silent correction is for the most recent version, but maybe I should scrap that plan). To not deposit for new versions of existing articles might get a little more tricky. If the article XML indicates when this is the situation would be good. If that isn't possible, we might need to consult and external data source like Lax or Crossref itself to see if the article previously had an component DOIs and then to withhold depositing to Crossref again.

**Comment by Melissa37** [comment]
>If they are "sticky" and live on even after simpler deposits then it might be less work required on our part.

I have asked the question.

The more I think about this the more complexity I see - for instance new versions make old versions a different URL, so we'd need to update the component DOI urls to point to the previous version anyhow? And what if we version a few and the previous version has no component DOIs either...
Shall we talk this through on our next call?
M

**Comment by gnott** [comment]
I agree we should probably look at it closely to not miss something. 

Accounting for old component DOI values might be handled on the journal side of things with redirects. I think we just deposit non-versioned URLs to Crossref for articles. 

The thing that does depend on the version number is the text and data mining values for the particular PDF and XML file, but those are not affected by component DOI values.

**Comment by Melissa37** [comment]
From crossref:

>The Component DOIs will remain registered and will remain associated with the same parent DOIs, whether or not the most recent metadata deposits for the parent DOIs' metadata contain the components.  


If we did not redeposit component DOIs they would direct to the most recent version of the site, but it would not contain a link to a DOI. Is this a problem though?

**Comment by gnott** [comment]
> If we did not redeposit component DOIs they would direct to the most recent version of the site, but it would not contain a link to a DOI. Is this a problem though?

I think it will not matter, as long as the request for that component DOI leads them to the article itself in some manner.

**Comment by Melissa37** [comment]
Cool, then we don't need to change anything in the Crossref code - it will pick up what's there in the JATS and send it across to Crossref?

**Comment by gnott** [comment]
@Melissa37 a question, when thinking about how the DOI value on peer review materials can be set by formula in the `decision-letter-parser` library.

If, in the future, there could be more than two peer reviews for an article, would it be possible and a good idea to base the DOI value on the `id` of the `<sub-article>`.

So instead of your examples,

```
10.7554/eLife.42687.DL
10.7554/eLife.42687.AR
```

it would be

```
10.7554/eLife.42687.sa1
10.7554/eLife.42687.sa2
```

**Comment by gnott** [comment]
In reference to my above comment, I am now thinking the `id` value may not make sense if the peer review materials existed outside of the main article XML, since an id of `sa2` only has significance when it exists along side the `sa1` and the main research article. (I hope that makes sense). Another way to phrase my question is, how would you assign the DOI values if you potentially had more than one decision letter? `10.7554/eLife.42687.DL1` and `10.7554/eLife.42687.DL2` ?

**Comment by Melissa37** [comment]
@gnott The DOI structure does not have to make sense to anyone and so whatever is easiest for us to implement and future proof it works for me!
I like your initial idea of <.sa1> suffix

The future might have individual reviews being published, and they would not be decision letters or author responses so keeping the suffixes generic to "sa" means we're not tying ourselves to one type of thing.

I'll let Exeter know this on the call today :-)

M

**Comment by gnott** [comment]
Older issue, I think this is all completed now, closing!
